package server

import (
	"net/http"
	"strconv"

	"github.com/hzx/matchengine/internal/engine"
	"github.com/hzx/matchengine/internal/models"
	"github.com/labstack/echo/v4"
	"github.com/shopspring/decimal"
	"go.uber.org/zap"
)

// HTTPServer HTTP服务器
type HTTPServer struct {
	engine *engine.Engine
	logger *zap.Logger
	echo   *echo.Echo
}

// NewEchoServer 创建Echo服务器
func NewEchoServer(matchingEngine *engine.Engine, logger *zap.Logger) *echo.Echo {
	s := &HTTPServer{
		engine: matchingEngine,
		logger: logger,
		echo:   echo.New(),
	}

	// 设置路由
	s.setupRoutes()

	return s.echo
}

// setupRoutes 设置路由
func (s *HTTPServer) setupRoutes() {
	// 健康检查
	s.echo.GET("/health", s.healthCheck)

	// 订单API
	s.echo.POST("/api/v1/order", s.createOrder)
	s.echo.DELETE("/api/v1/order/:symbol/:order_id", s.cancelOrder)
	s.echo.GET("/api/v1/order/:symbol/:order_id", s.getOrder)
	s.echo.GET("/api/v1/orders/:user_id", s.getUserOrders)

	// 市场数据API
	s.echo.GET("/api/v1/depth/:symbol", s.getDepth)
	s.echo.GET("/api/v1/ticker/:symbol", s.getTicker)
	s.echo.GET("/api/v1/trades/:symbol", s.getTrades)
}

// healthCheck 健康检查
func (s *HTTPServer) healthCheck(c echo.Context) error {
	return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
}

// createOrder 创建订单
func (s *HTTPServer) createOrder(c echo.Context) error {
	var req CreateOrderRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": err.Error()})
	}

	// 验证参数
	if req.UserID == 0 || req.Symbol == "" {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid parameters"})
	}

	// 解析价格和数量
	price, err := decimal.NewFromString(req.Price)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid price"})
	}

	amount, err := decimal.NewFromString(req.Amount)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid amount"})
	}

	// 创建订单
	order := models.NewOrder(
		0, // ID will be generated by engine
		req.UserID,
		req.Symbol,
		models.OrderSide(req.Side),
		models.OrderType(req.Type),
		price,
		amount,
		models.TimeInForce(req.TimeInForce),
	)

	// 提交订单
	if err := s.engine.SubmitOrder(order); err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": err.Error()})
	}

	return c.JSON(http.StatusOK, order)
}

// cancelOrder 取消订单
func (s *HTTPServer) cancelOrder(c echo.Context) error {
	symbol := c.Param("symbol")
	orderIDStr := c.Param("order_id")

	orderID, err := strconv.ParseUint(orderIDStr, 10, 64)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid order id"})
	}

	order, err := s.engine.CancelOrder(symbol, orderID)
	if err != nil {
		return c.JSON(http.StatusNotFound, map[string]string{"error": err.Error()})
	}

	return c.JSON(http.StatusOK, order)
}

// getOrder 获取订单
func (s *HTTPServer) getOrder(c echo.Context) error {
	symbol := c.Param("symbol")
	orderIDStr := c.Param("order_id")

	orderID, err := strconv.ParseUint(orderIDStr, 10, 64)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid order id"})
	}

	order, err := s.engine.GetOrder(symbol, orderID)
	if err != nil {
		return c.JSON(http.StatusNotFound, map[string]string{"error": err.Error()})
	}

	return c.JSON(http.StatusOK, order)
}

// getUserOrders 获取用户订单
func (s *HTTPServer) getUserOrders(c echo.Context) error {
	userIDStr := c.Param("user_id")
	userID, err := strconv.ParseUint(userIDStr, 10, 64)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid user id"})
	}

	symbol := c.QueryParam("symbol")
	limit, _ := strconv.Atoi(c.QueryParam("limit"))
	if limit == 0 {
		limit = 20
	}

	// TODO: 实现从数据库查询
	orders := make([]*models.Order, 0)

	return c.JSON(http.StatusOK, map[string]interface{}{
		"user_id": userID,
		"symbol":  symbol,
		"orders":  orders,
	})
}

// getDepth 获取盘口深度
func (s *HTTPServer) getDepth(c echo.Context) error {
	symbol := c.Param("symbol")
	limit, _ := strconv.Atoi(c.QueryParam("limit"))
	if limit == 0 {
		limit = 20
	}

	depth, err := s.engine.GetDepth(symbol, limit)
	if err != nil {
		return c.JSON(http.StatusNotFound, map[string]string{"error": err.Error()})
	}

	return c.JSON(http.StatusOK, depth)
}

// getTicker 获取行情
func (s *HTTPServer) getTicker(c echo.Context) error {
	symbol := c.Param("symbol")

	ticker, err := s.engine.GetTicker(symbol)
	if err != nil {
		return c.JSON(http.StatusNotFound, map[string]string{"error": err.Error()})
	}

	return c.JSON(http.StatusOK, ticker)
}

// getTrades 获取成交记录
func (s *HTTPServer) getTrades(c echo.Context) error {
	symbol := c.Param("symbol")
	limit, _ := strconv.Atoi(c.QueryParam("limit"))
	if limit == 0 {
		limit = 100
	}

	// TODO: 实现从数据库查询
	trades := make([]*models.Trade, 0)

	return c.JSON(http.StatusOK, map[string]interface{}{
		"symbol": symbol,
		"trades": trades,
	})
}

// CreateOrderRequest 创建订单请求
type CreateOrderRequest struct {
	UserID      uint64 `json:"user_id"`
	Symbol      string `json:"symbol"`
	Side        int    `json:"side"`         // 1=buy, 2=sell
	Type        int    `json:"type"`         // 1=limit, 2=market, etc.
	Price       string `json:"price"`
	Amount      string `json:"amount"`
	TimeInForce int    `json:"time_in_force"` // 1=GTC, 2=IOC, 3=FOK, 4=GTX
}
