// Code generated by protoc-gen-go. DO NOT EDIT.
package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// OrderSide 订单方向
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNKNOWN OrderSide = 0
	OrderSide_ORDER_SIDE_BUY     OrderSide = 1
	OrderSide_ORDER_SIDE_SELL    OrderSide = 2
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	switch x {
	case OrderSide_ORDER_SIDE_UNKNOWN:
		return "ORDER_SIDE_UNKNOWN"
	case OrderSide_ORDER_SIDE_BUY:
		return "ORDER_SIDE_BUY"
	case OrderSide_ORDER_SIDE_SELL:
		return "ORDER_SIDE_SELL"
	default:
		return "ORDER_SIDE_UNKNOWN"
	}
}

// OrderType 订单类型
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNKNOWN     OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
	OrderType_ORDER_TYPE_STOP_LIMIT  OrderType = 3
	OrderType_ORDER_TYPE_STOP_MARKET OrderType = 4
	OrderType_ORDER_TYPE_ICEBERG     OrderType = 5
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	switch x {
	case OrderType_ORDER_TYPE_UNKNOWN:
		return "ORDER_TYPE_UNKNOWN"
	case OrderType_ORDER_TYPE_LIMIT:
		return "ORDER_TYPE_LIMIT"
	case OrderType_ORDER_TYPE_MARKET:
		return "ORDER_TYPE_MARKET"
	case OrderType_ORDER_TYPE_STOP_LIMIT:
		return "ORDER_TYPE_STOP_LIMIT"
	case OrderType_ORDER_TYPE_STOP_MARKET:
		return "ORDER_TYPE_STOP_MARKET"
	case OrderType_ORDER_TYPE_ICEBERG:
		return "ORDER_TYPE_ICEBERG"
	default:
		return "ORDER_TYPE_UNKNOWN"
	}
}

// OrderStatus 订单状态
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNKNOWN   OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING   OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIAL   OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED OrderStatus = 4
	OrderStatus_ORDER_STATUS_REJECTED  OrderStatus = 5
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	switch x {
	case OrderStatus_ORDER_STATUS_UNKNOWN:
		return "ORDER_STATUS_UNKNOWN"
	case OrderStatus_ORDER_STATUS_PENDING:
		return "ORDER_STATUS_PENDING"
	case OrderStatus_ORDER_STATUS_PARTIAL:
		return "ORDER_STATUS_PARTIAL"
	case OrderStatus_ORDER_STATUS_FILLED:
		return "ORDER_STATUS_FILLED"
	case OrderStatus_ORDER_STATUS_CANCELLED:
		return "ORDER_STATUS_CANCELLED"
	case OrderStatus_ORDER_STATUS_REJECTED:
		return "ORDER_STATUS_REJECTED"
	default:
		return "ORDER_STATUS_UNKNOWN"
	}
}

// TimeInForce 订单有效期类型
type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNKNOWN TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC     TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC     TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK     TimeInForce = 3
	TimeInForce_TIME_IN_FORCE_GTX     TimeInForce = 4
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	switch x {
	case TimeInForce_TIME_IN_FORCE_UNKNOWN:
		return "TIME_IN_FORCE_UNKNOWN"
	case TimeInForce_TIME_IN_FORCE_GTC:
		return "TIME_IN_FORCE_GTC"
	case TimeInForce_TIME_IN_FORCE_IOC:
		return "TIME_IN_FORCE_IOC"
	case TimeInForce_TIME_IN_FORCE_FOK:
		return "TIME_IN_FORCE_FOK"
	case TimeInForce_TIME_IN_FORCE_GTX:
		return "TIME_IN_FORCE_GTX"
	default:
		return "TIME_IN_FORCE_UNKNOWN"
	}
}

// SubmitOrderRequest 提交订单请求
type SubmitOrderRequest struct {
	UserId        uint64
	Symbol        string
	Side          OrderSide
	Type          OrderType
	Price         string
	Amount        string
	TimeInForce   TimeInForce
	StopPrice     string
	VisibleAmount string
}

func (x *SubmitOrderRequest) Reset()         { *x = SubmitOrderRequest{} }
func (x *SubmitOrderRequest) String() string { return "SubmitOrderRequest" }
func (x *SubmitOrderRequest) ProtoMessage()  {}

func (x *SubmitOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNKNOWN
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNKNOWN
}

func (x *SubmitOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SubmitOrderRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SubmitOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNKNOWN
}

func (x *SubmitOrderRequest) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *SubmitOrderRequest) GetVisibleAmount() string {
	if x != nil {
		return x.VisibleAmount
	}
	return ""
}

// SubmitOrderResponse 提交订单响应
type SubmitOrderResponse struct {
	Success bool
	Error   string
	Order   *Order
}

func (x *SubmitOrderResponse) Reset()         { *x = SubmitOrderResponse{} }
func (x *SubmitOrderResponse) String() string { return "SubmitOrderResponse" }
func (x *SubmitOrderResponse) ProtoMessage()  {}

func (x *SubmitOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SubmitOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// CancelOrderRequest 取消订单请求
type CancelOrderRequest struct {
	Symbol  string
	OrderId uint64
}

func (x *CancelOrderRequest) Reset()         { *x = CancelOrderRequest{} }
func (x *CancelOrderRequest) String() string { return "CancelOrderRequest" }
func (x *CancelOrderRequest) ProtoMessage()  {}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// CancelOrderResponse 取消订单响应
type CancelOrderResponse struct {
	Success bool
	Error   string
	Order   *Order
}

func (x *CancelOrderResponse) Reset()         { *x = CancelOrderResponse{} }
func (x *CancelOrderResponse) String() string { return "CancelOrderResponse" }
func (x *CancelOrderResponse) ProtoMessage()  {}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// GetOrderRequest 获取订单请求
type GetOrderRequest struct {
	Symbol  string
	OrderId uint64
}

func (x *GetOrderRequest) Reset()         { *x = GetOrderRequest{} }
func (x *GetOrderRequest) String() string { return "GetOrderRequest" }
func (x *GetOrderRequest) ProtoMessage()  {}

func (x *GetOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// GetOrderResponse 获取订单响应
type GetOrderResponse struct {
	Success bool
	Error   string
	Order   *Order
}

func (x *GetOrderResponse) Reset()         { *x = GetOrderResponse{} }
func (x *GetOrderResponse) String() string { return "GetOrderResponse" }
func (x *GetOrderResponse) ProtoMessage()  {}

func (x *GetOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// GetDepthRequest 获取盘口深度请求
type GetDepthRequest struct {
	Symbol string
	Limit  int32
}

func (x *GetDepthRequest) Reset()         { *x = GetDepthRequest{} }
func (x *GetDepthRequest) String() string { return "GetDepthRequest" }
func (x *GetDepthRequest) ProtoMessage()  {}

func (x *GetDepthRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetDepthResponse 获取盘口深度响应
type GetDepthResponse struct {
	Success bool
	Error   string
	Symbol  string
	Bids    []*DepthLevel
	Asks    []*DepthLevel
}

func (x *GetDepthResponse) Reset()         { *x = GetDepthResponse{} }
func (x *GetDepthResponse) String() string { return "GetDepthResponse" }
func (x *GetDepthResponse) ProtoMessage()  {}

func (x *GetDepthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDepthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetDepthResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthResponse) GetBids() []*DepthLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetDepthResponse) GetAsks() []*DepthLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// DepthLevel 盘口价格档位
type DepthLevel struct {
	Price  string
	Amount string
}

func (x *DepthLevel) Reset()         { *x = DepthLevel{} }
func (x *DepthLevel) String() string { return "DepthLevel" }
func (x *DepthLevel) ProtoMessage()  {}

func (x *DepthLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DepthLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// GetTickerRequest 获取行情请求
type GetTickerRequest struct {
	Symbol string
}

func (x *GetTickerRequest) Reset()         { *x = GetTickerRequest{} }
func (x *GetTickerRequest) String() string { return "GetTickerRequest" }
func (x *GetTickerRequest) ProtoMessage()  {}

func (x *GetTickerRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetTickerResponse 获取行情响应
type GetTickerResponse struct {
	Success bool
	Error   string
	Ticker  *Ticker
}

func (x *GetTickerResponse) Reset()         { *x = GetTickerResponse{} }
func (x *GetTickerResponse) String() string { return "GetTickerResponse" }
func (x *GetTickerResponse) ProtoMessage()  {}

func (x *GetTickerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTickerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTickerResponse) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

// Ticker 行情
type Ticker struct {
	Symbol    string
	LastPrice string
	BidPrice  string
	BidAmount string
	AskPrice  string
	AskAmount string
	Timestamp int64
}

func (x *Ticker) Reset()         { *x = Ticker{} }
func (x *Ticker) String() string { return "Ticker" }
func (x *Ticker) ProtoMessage()  {}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Ticker) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *Ticker) GetBidAmount() string {
	if x != nil {
		return x.BidAmount
	}
	return ""
}

func (x *Ticker) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *Ticker) GetAskAmount() string {
	if x != nil {
		return x.AskAmount
	}
	return ""
}

func (x *Ticker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetTradesRequest 获取成交记录请求
type GetTradesRequest struct {
	Symbol string
	Limit  int32
	Offset int32
}

func (x *GetTradesRequest) Reset()         { *x = GetTradesRequest{} }
func (x *GetTradesRequest) String() string { return "GetTradesRequest" }
func (x *GetTradesRequest) ProtoMessage()  {}

func (x *GetTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTradesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetTradesResponse 获取成交记录响应
type GetTradesResponse struct {
	Success bool
	Error   string
	Trades  []*Trade
}

func (x *GetTradesResponse) Reset()         { *x = GetTradesResponse{} }
func (x *GetTradesResponse) String() string { return "GetTradesResponse" }
func (x *GetTradesResponse) ProtoMessage()  {}

func (x *GetTradesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTradesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Trade 成交记录
type Trade struct {
	Id           uint64
	TakerOrderId uint64
	MakerOrderId uint64
	UserId       uint64
	MakerUserId  uint64
	Symbol       string
	Price        string
	Amount       string
	Total        string
	Fee          string
	FeeAsset     string
	Side         OrderSide
	CreatedAt    int64
}

func (x *Trade) Reset()         { *x = Trade{} }
func (x *Trade) String() string { return "Trade" }
func (x *Trade) ProtoMessage()  {}

func (x *Trade) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetTakerOrderId() uint64 {
	if x != nil {
		return x.TakerOrderId
	}
	return 0
}

func (x *Trade) GetMakerOrderId() uint64 {
	if x != nil {
		return x.MakerOrderId
	}
	return 0
}

func (x *Trade) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Trade) GetMakerUserId() uint64 {
	if x != nil {
		return x.MakerUserId
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Trade) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *Trade) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Trade) GetFeeAsset() string {
	if x != nil {
		return x.FeeAsset
	}
	return ""
}

func (x *Trade) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNKNOWN
}

func (x *Trade) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Order 订单
type Order struct {
	Id            uint64
	UserId        uint64
	Symbol        string
	Side          OrderSide
	Type          OrderType
	Status        OrderStatus
	Price         string
	Amount        string
	FilledAmount  string
	RemainAmount  string
	FilledTotal   string
	Fee           string
	FeeAsset      string
	TimeInForce   TimeInForce
	StopPrice     string
	VisibleAmount string
	CreatedAt     int64
	UpdatedAt     int64
}

func (x *Order) Reset()         { *x = Order{} }
func (x *Order) String() string { return "Order" }
func (x *Order) ProtoMessage()  {}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNKNOWN
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNKNOWN
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNKNOWN
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Order) GetFilledAmount() string {
	if x != nil {
		return x.FilledAmount
	}
	return ""
}

func (x *Order) GetRemainAmount() string {
	if x != nil {
		return x.RemainAmount
	}
	return ""
}

func (x *Order) GetFilledTotal() string {
	if x != nil {
		return x.FilledTotal
	}
	return ""
}

func (x *Order) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Order) GetFeeAsset() string {
	if x != nil {
		return x.FeeAsset
	}
	return ""
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNKNOWN
}

func (x *Order) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *Order) GetVisibleAmount() string {
	if x != nil {
		return x.VisibleAmount
	}
	return ""
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// MatchEngineServer is the server API for MatchEngine service.
type MatchEngineServer interface {
	SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetDepth(context.Context, *GetDepthRequest) (*GetDepthResponse, error)
	GetTicker(context.Context, *GetTickerRequest) (*GetTickerResponse, error)
	GetTrades(context.Context, *GetTradesRequest) (*GetTradesResponse, error)
}

// UnimplementedMatchEngineServer can be embedded to have forward compatible implementations.
type UnimplementedMatchEngineServer struct{}

func (UnimplementedMatchEngineServer) SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedMatchEngineServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatchEngineServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedMatchEngineServer) GetDepth(context.Context, *GetDepthRequest) (*GetDepthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepth not implemented")
}
func (UnimplementedMatchEngineServer) GetTicker(context.Context, *GetTickerRequest) (*GetTickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicker not implemented")
}
func (UnimplementedMatchEngineServer) GetTrades(context.Context, *GetTradesRequest) (*GetTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrades not implemented")
}

// RegisterMatchEngineServer registers a server implementation.
func RegisterMatchEngineServer(s grpc.ServiceRegistrar, srv MatchEngineServer) {
	s.RegisterService(&MatchEngine_ServiceDesc, srv)
}

var MatchEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.MatchEngine",
	HandlerType: (*MatchEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _MatchEngine_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatchEngine_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _MatchEngine_GetOrder_Handler,
		},
		{
			MethodName: "GetDepth",
			Handler:    _MatchEngine_GetDepth_Handler,
		},
		{
			MethodName: "GetTicker",
			Handler:    _MatchEngine_GetTicker_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _MatchEngine_GetTrades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchengine.proto",
}

func _MatchEngine_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).SubmitOrder(ctx, req.(*SubmitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/GetDepth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetDepth(ctx, req.(*GetDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/GetTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetTicker(ctx, req.(*GetTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MatchEngine/GetTrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetTrades(ctx, req.(*GetTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchEngineClient is the client API for MatchEngine service.
type MatchEngineClient interface {
	SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	GetDepth(ctx context.Context, in *GetDepthRequest, opts ...grpc.CallOption) (*GetDepthResponse, error)
	GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error)
	GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error)
}

type matchEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchEngineClient(cc grpc.ClientConnInterface) MatchEngineClient {
	return &matchEngineClient{cc}
}

func (c *matchEngineClient) SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error) {
	out := new(SubmitOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetDepth(ctx context.Context, in *GetDepthRequest, opts ...grpc.CallOption) (*GetDepthResponse, error) {
	out := new(GetDepthResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/GetDepth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error) {
	out := new(GetTickerResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/GetTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error) {
	out := new(GetTradesResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MatchEngine/GetTrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
